# This is a workflow to publish the react application to the kubernetes.

name: Akash-Build

# Controls when the workflow will run
on:
  release:
    types: [released]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  app-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.15
        uses: actions/setup-node@v2
        with:
          node-version: '16.15'

      - name: Prep for build
        run: |
          touch .env
          echo REACT_APP_RPC_URL=${{ secrets.REACT_APP_RPC_URL }} >> .env
          echo REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL_PRD }} >> .env
          echo REACT_APP_AUTH_URL=${{ secrets.REACT_APP_AUTH_URL_PRD }} >> .env
          yarn install

      - name: Production Build
        run: |
          yarn build

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build and push
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t ${{ secrets.DOCKERHUB_ORGANIZATION }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.RELEASE_VERSION }} .
          docker push ${{ secrets.DOCKERHUB_ORGANIZATION }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.RELEASE_VERSION }}
